name: mcpose CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mcpose
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: mcpose/package-lock.json
      - run: npm ci
      - name: Type check
        run: npm run ts:ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
